import type { DetectedExport, NormalizedPage } from "@/types/seo";

export function buildMockPages(): NormalizedPage[] {
  return [
    {
      url: "https://nordiccommerce.com/",
      path: "/",
      template: "Homepage",
      statusCode: 200,
      title: "Nordic Commerce Platform | Enterprise Growth Systems",
      titleLength: 51,
      h1: "Enterprise growth systems for modern retail teams",
      canonical: "https://nordiccommerce.com/",
      crawlDepth: 0,
      inlinks: 84,
      indexability: true,
      wordCount: 1180,
      hasStructuredData: true,
    },
    {
      url: "https://nordiccommerce.com/services/technical-seo",
      path: "/services/technical-seo",
      template: "Service",
      statusCode: 200,
      title: "Technical SEO Consulting for Enterprise Teams",
      titleLength: 44,
      h1: "Technical SEO consulting",
      canonical: "https://nordiccommerce.com/services/technical-seo",
      crawlDepth: 2,
      inlinks: 24,
      indexability: true,
      wordCount: 920,
      hasStructuredData: true,
    },
    {
      url: "https://nordiccommerce.com/services/content-operations",
      path: "/services/content-operations",
      template: "Service",
      statusCode: 200,
      title: "Enterprise SEO Services",
      titleLength: 23,
      h1: "Enterprise SEO services",
      canonical: "https://nordiccommerce.com/services/content-operations",
      crawlDepth: 3,
      inlinks: 7,
      indexability: true,
      wordCount: 860,
      hasStructuredData: true,
    },
    {
      url: "https://nordiccommerce.com/services/international-seo",
      path: "/services/international-seo",
      template: "Service",
      statusCode: 200,
      title: "Enterprise SEO Services",
      titleLength: 23,
      h1: "International SEO consulting",
      canonical: "https://nordiccommerce.com/services/international-seo",
      crawlDepth: 3,
      inlinks: 5,
      indexability: true,
      wordCount: 840,
      hasStructuredData: false,
    },
    {
      url: "https://nordiccommerce.com/category/homeware",
      path: "/category/homeware",
      template: "Category",
      statusCode: 200,
      title: "Shop Scandinavian Homeware Collections Online Today",
      titleLength: 53,
      h1: "Scandinavian homeware",
      canonical: "https://nordiccommerce.com/category/homeware",
      crawlDepth: 4,
      inlinks: 2,
      indexability: true,
      wordCount: 410,
      hasStructuredData: true,
    },
    {
      url: "https://nordiccommerce.com/category/lighting",
      path: "/category/lighting",
      template: "Category",
      statusCode: 200,
      title: "Shop Scandinavian Homeware Collections Online Today",
      titleLength: 53,
      h1: "Lighting",
      canonical: "https://nordiccommerce.com/category/lighting",
      crawlDepth: 4,
      inlinks: 1,
      indexability: true,
      wordCount: 395,
      hasStructuredData: false,
    },
    {
      url: "https://nordiccommerce.com/category/furniture",
      path: "/category/furniture",
      template: "Category",
      statusCode: 200,
      title: "Minimalist Furniture for Calm Interiors and Modern Homes",
      titleLength: 58,
      h1: "Furniture",
      canonical: "https://nordiccommerce.com/category/furniture",
      crawlDepth: 5,
      inlinks: 0,
      indexability: true,
      wordCount: 380,
      hasStructuredData: false,
    },
    {
      url: "https://nordiccommerce.com/category/textiles",
      path: "/category/textiles",
      template: "Category",
      statusCode: 200,
      title: "Minimalist Textiles and Soft Furnishings for Nordic Homes",
      titleLength: 57,
      h1: "Textiles",
      canonical: "",
      crawlDepth: 5,
      inlinks: 1,
      indexability: true,
      wordCount: 210,
      hasStructuredData: false,
    },
    {
      url: "https://nordiccommerce.com/blog/technical-seo-governance",
      path: "/blog/technical-seo-governance",
      template: "Editorial",
      statusCode: 200,
      title: "Technical SEO Governance for Multi-Market Platforms and Operations",
      titleLength: 66,
      h1: "Technical SEO governance",
      canonical: "https://nordiccommerce.com/blog/technical-seo-governance",
      crawlDepth: 3,
      inlinks: 6,
      indexability: true,
      wordCount: 1450,
      hasStructuredData: true,
    },
    {
      url: "https://nordiccommerce.com/blog/template-governance",
      path: "/blog/template-governance",
      template: "Editorial",
      statusCode: 200,
      title: "",
      titleLength: 0,
      h1: "Template governance in search operations",
      canonical: "https://nordiccommerce.com/blog/template-governance",
      crawlDepth: 3,
      inlinks: 2,
      indexability: true,
      wordCount: 1320,
      hasStructuredData: true,
    },
    {
      url: "https://nordiccommerce.com/blog/internal-linking",
      path: "/blog/internal-linking",
      template: "Editorial",
      statusCode: 200,
      title: "Internal Linking for Growth Teams",
      titleLength: 32,
      h1: "Internal linking for growth teams",
      canonical: "https://nordiccommerce.com/blog/internal-linking",
      crawlDepth: 4,
      inlinks: 1,
      indexability: true,
      wordCount: 820,
      hasStructuredData: true,
    },
    {
      url: "https://nordiccommerce.com/resources/site-migration-checklist",
      path: "/resources/site-migration-checklist",
      template: "Resource",
      statusCode: 200,
      title: "Site migration checklist for enterprise ecommerce teams",
      titleLength: 55,
      h1: "",
      canonical: "https://nordiccommerce.com/resources/site-migration-checklist",
      crawlDepth: 4,
      inlinks: 0,
      indexability: true,
      wordCount: 760,
      hasStructuredData: true,
    },
    {
      url: "https://nordiccommerce.com/resources/canonical-playbook",
      path: "/resources/canonical-playbook",
      template: "Resource",
      statusCode: 200,
      title: "Canonical playbook for enterprise ecommerce teams",
      titleLength: 48,
      h1: "Canonical governance playbook",
      canonical: "https://nordiccommerce.com/resources/canonical-playbook?ref=nav",
      crawlDepth: 5,
      inlinks: 1,
      indexability: true,
      wordCount: 540,
      hasStructuredData: true,
    },
    {
      url: "https://nordiccommerce.com/resources/redirect-mapping",
      path: "/resources/redirect-mapping",
      template: "Resource",
      statusCode: 302,
      title: "Redirect mapping workbook",
      titleLength: 25,
      h1: "Redirect mapping workbook",
      canonical: "https://nordiccommerce.com/resources/redirect-mapping",
      crawlDepth: 4,
      inlinks: 3,
      indexability: false,
      wordCount: 0,
      redirectUrl: "https://nordiccommerce.com/resources/redirect-governance",
      hasStructuredData: false,
    },
    {
      url: "https://nordiccommerce.com/resources/legacy-template-guide",
      path: "/resources/legacy-template-guide",
      template: "Resource",
      statusCode: 404,
      title: "Legacy template guide",
      titleLength: 21,
      h1: "Legacy template guide",
      canonical: "https://nordiccommerce.com/resources/legacy-template-guide",
      crawlDepth: 3,
      inlinks: 4,
      indexability: false,
      wordCount: 0,
      hasStructuredData: false,
    },
    {
      url: "https://nordiccommerce.com/category/storage?sort=popular",
      path: "/category/storage?sort=popular",
      template: "Category",
      statusCode: 200,
      title: "Storage",
      titleLength: 7,
      h1: "Storage",
      canonical: "",
      crawlDepth: 5,
      inlinks: 0,
      indexability: false,
      wordCount: 180,
      hasStructuredData: false,
    },
    {
      url: "https://nordiccommerce.com/category/storage",
      path: "/category/storage",
      template: "Category",
      statusCode: 200,
      title: "Storage",
      titleLength: 7,
      h1: "Storage",
      canonical: "https://nordiccommerce.com/category/storage",
      crawlDepth: 4,
      inlinks: 2,
      indexability: true,
      wordCount: 240,
      hasStructuredData: false,
    },
    {
      url: "https://nordiccommerce.com/services/platform-migrations",
      path: "/services/platform-migrations",
      template: "Service",
      statusCode: 200,
      title: "Platform migration consulting for search-led commerce programs",
      titleLength: 63,
      h1: "Platform migration consulting",
      canonical: "https://nordiccommerce.com/services/platform-migrations",
      crawlDepth: 2,
      inlinks: 5,
      indexability: true,
      wordCount: 910,
      hasStructuredData: true,
    },
    {
      url: "https://nordiccommerce.com/services/site-architecture",
      path: "/services/site-architecture",
      template: "Service",
      statusCode: 200,
      title: "Site architecture consulting for enterprise catalogue teams",
      titleLength: 58,
      h1: "Platform migration consulting",
      canonical: "https://nordiccommerce.com/services/site-architecture",
      crawlDepth: 3,
      inlinks: 3,
      indexability: true,
      wordCount: 890,
      hasStructuredData: true,
    },
    {
      url: "https://nordiccommerce.com/resources/collection-governance",
      path: "/resources/collection-governance",
      template: "Resource",
      statusCode: 200,
      title: "Collection governance framework",
      titleLength: 29,
      h1: "Collection governance framework",
      canonical: "https://nordiccommerce.com/resources/collection-governance",
      crawlDepth: 5,
      inlinks: 2,
      indexability: true,
      wordCount: 230,
      hasStructuredData: false,
    },
  ];
}

export function buildMockDetectedExports(): DetectedExport[] {
  const timestamp = new Date().toISOString();
  return [
    ["internal_html", "internal_html.csv", "Internal HTML"],
    ["response_codes", "response_codes.csv", "Response Codes"],
    ["page_titles", "page_titles.csv", "Page Titles"],
    ["h1", "h1.csv", "H1"],
    ["canonicals", "canonicals.csv", "Canonicals"],
    ["inlinks", "inlinks.csv", "Inlinks"],
    ["crawl_overview", "crawl_overview.csv", "Crawl Overview"],
  ].map(([exportType, fileName, label]) => ({
    exportType: exportType as DetectedExport["exportType"],
    fileName,
    label,
    uploadedAt: timestamp,
  }));
}
